### ISSUE TITLE
Option to send as regular text

### ISSUE THREAD

**Issue by hw-0** [jakobdylanc/discord-llm-chatbot#30]
Hello, I was messing around with your bot and comparing it to [chrisrude's oobabot](https://github.com/chrisrude/oobabot) plugin (when it was functional) for textgen webui. One thing that I think would enhance this software would be giving the bot the option to send as regular text like in oobabot or have the option to send it as embeds like what is currently possible in this software.

**Comment by jakobdylanc** [comment]
Thanks for the suggestion! You're actually the second person to request this.

I'm curious, what downsides do you see in embeds? What makes you want this in general?

**Comment by hw-0** [comment]
In general, I don't really see any downsides to using the embeds I think they are actually quite useful for people who might not realize they're talking to a bot (lol) or for using it as intelligent QA replying. For me personally the reason I prefer using chat based compared to embeds is due to it feeling more natural if you're using it more as a chatbot. Where as with the embeds sometimes it feels more like QA than a natural chat. That's why I think there should be an option to have either as it can be more versatile in specific use cases.

**Comment by jakobdylanc** [comment]
I chose to use embeds because of their various advantages like:
- Much higher character limit (4096) vs. regular messages (2000)
- A "color" parameter that I use as a helpful indicator for streaming status (orange=generating, green=done)
- Extra fields that I use for user warning messages (e.g. "⚠️ Only using last 20 messages" when MAX_MESSAGES is exceeded)

The character limit alone makes me strongly prefer embeds. I see your points though.

**Comment by jakobdylanc** [comment]
This feature is now added via a new "use_plain_responses" config option.
