### ISSUE TITLE
possible to change formatting of text?

### ISSUE THREAD

**Issue by chaowss** [jakobdylanc/discord-llm-chatbot#42]
text comes out as embed, is there a way to do it so it doesn't?

**Comment by jakobdylanc** [comment]
I chose to use embeds because of their various advantages like:
- Much higher character limit (4096) vs. regular messages (2000)
- A "color" parameter that I use as a helpful indicator for streaming status (orange=generating, green=done)
- Extra fields that I use for user warning messages (e.g. `⚠️ Only using last 20 messages` when MAX_MESSAGES is exceeded)

Can I ask, why don't you want embeds?

**Comment by jakobdylanc** [comment]
I don't plan on making embeds optional due to the advantages I listed above. I'd also have to make streamed responses optional, because otherwise the bot's messages still wouldn't look "human". And without streamed responses you need an entirely different way to handle the case where the bot's message gets too long for a single message. You'd think "just split it up!" but you risk cutting words in half without a custom splitting function.

So yeah, in the interest of simplicity, I don't want to open up this rabbit hole :)

**Comment by jakobdylanc** [comment]
This feature is now added via a new "use_plain_responses" config option.

**Comment by chaowss** [comment]
awesome! thanks
