### ISSUE TITLE
Ability to use plain text instead?

### ISSUE THREAD

**Issue by pixelqiwi** [jakobdylanc/discord-llm-chatbot#50]
The title. Like, I get that you can show more info with the embeds, i.e. the colour of it and the title and whatnot, but would it be possible to use plain text messages for the LLM responses so it looks more believable in the context of a discord chat?

**Comment by jakobdylanc** [comment]
When you say "more believable" do you mean no streamed responses either? E.g. just a regular message that sends all at once?

**Comment by pixelqiwi** [comment]
possibly, yes

**Comment by jakobdylanc** [comment]
Yeah, I think in order to do it perfectly I'd have to make streamed responses optional too. This is just another thing that I'm indecisive on exactly how to implement. I want to make sure I do it right the first time so I don't have to change my mind later.

I could add 2 new boolean config options, "USE_STREAMED_RESPONSES" and "USE_EMBEDS". But I see little use in them being separate since I think most users would want them both either turned on or turned off. So I've also considered creating an entirely separate "llmcord-lite.py" file that is a bare minimum version of llmcord.py, e.g. no embeds or streamed responses. But I don't like duplication.

There's also some finer details that makes implementing all of this a little tricky, at least without it being sloppy.

So...I'm indecisive about it. Open to thoughts.

**Comment by pixelqiwi** [comment]
from my unprofessional point of view i think it's would be best to make these things optional, because you can never truly know *all* the ways people would want to use it, like some people prefer to see the streamed responses, some people like fancy embeds (i remember back in the day people used to download third-party discord clients just to show off by sending embeds themselves), and so on. 

not sure that making a separate project for a lighter looking version of this is a good approach, think of it as customisation options instead. imagine if there was a separate client for every discord Appearance settings option.

as for the 2-in-1 config option, if you decide to do it that way, it could be named something funny like "FANCY_MODE" or "BELLS_AND_WHISTLES", if you're into that :D

**Comment by jakobdylanc** [comment]
Finally added - check out the new "use_plain_responses" config option. Enjoy!
